version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    networks:
      rdb:
      sig:
      srv:
        aliases:
          - notary-server
    environment:
      - GODEBUG=netdns=cgo
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-server -config=fixtures/server-config.json"
    depends_on:
      - mysql
      - signer
  signer:
    build:
      context: .
      dockerfile: signer.Dockerfile
    networks:
      rdb:
      sig:
        aliases:
          - notarysigner
    environment:
      - GODEBUG=netdns=cgo
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-signer -config=fixtures/signer-config.json"
    depends_on:
      - mysql
  mysql:
    networks:
      - rdb
    volumes:
      - ./notarymysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    image: mariadb:10.1.10
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: mysqld --innodb_file_per_table
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GODEBUG=netdns=cgo
    command: buildscripts/testclient.sh
    volumes:
      - ./test_output:/test_output
    networks:
      - srv
    depends_on:
      - server
volumes:
  notary_data:
    external: false
networks:
  rdb:
    external: false
  sig:
    external: false
  srv:
    external: false
