notaryserver:
  build: .
  dockerfile: notary-server-Dockerfile
  links:
   - notarymysql
   - notarysigner
  ports:
   - "8080"
   - "4443:4443"
  environment:
    SERVICE_NAME: notary
notarysigner:
  volumes:
   - /dev/bus/usb/003/010:/dev/bus/usb/002/010
   - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
  build: .
  dockerfile: notary-signer-Dockerfile
  links:
   - notarymysql
notarymysql:
  build: ./notarymysql/
  ports:
    - "3306:3306"
  environment:
    - DB_NAME: development
    - DB_TABLE_FILES: tuf_files
    - DB_TABLE_KEYS: timestamp_keys
    - DB_USER: gordontheturtle
    - DB_PASS: dockerrulez
    - DB_REMOTE_ROOT_NAME: gordontheturtle
    - DB_REMOTE_ROOT_PASS: dockerrulez
    - DB_REMOTE_ROOT_HOST: ""
