notaryserver:
  build: .
  dockerfile: notary-server-Dockerfile
  links:
   - notarymysql
  ports:
   - "8080:8080"
   - "4443:4443"
notarysigner:
  volumes:
   - /dev/bus/usb/003/010:/dev/bus/usb/002/010
   - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
  build: .
  dockerfile: notary-signer-Dockerfile
notarymysql:
  build: ./notarymysql/
  ports:
    - "3306:3306"
