apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "notary.fullname" . }}-notarysql
data:
  {{- if eq .Values.databaseContainer.engine "mysql" }}
  {{- range $path, $bytes := .Files.Glob "notarysql/mysql-initdb.d/**" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
  {{- else if eq .Values.databaseContainer.engine "postgres" }}
  {{- range $path, $bytes := .Files.Glob "notarysql/postgresql-initdb.d/**" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
  {{- end }}


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "notary.fullname" . }}-migrations-server
data:
  {{- if eq .Values.databaseContainer.engine "mysql" }}
  {{- range $path, $bytes := .Files.Glob "migrations/server/mysql/**" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
  {{- else if eq .Values.databaseContainer.engine "postgres" }}
  {{- range $path, $bytes := .Files.Glob "migrations/server/postgresql/**" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
  {{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "notary.fullname" . }}-migrations-signer
data:
  {{- if eq .Values.databaseContainer.engine "mysql" }}
  {{- range $path, $bytes := .Files.Glob "migrations/signer/mysql/**" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
  {{- else if eq .Values.databaseContainer.engine "postgres" }}
  {{- range $path, $bytes := .Files.Glob "migrations/signer/postgresql/**" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
  {{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "notary.fullname" . }}-config
data:
  server-config.json: |
{{ tpl (.Files.Get "files/server-config.json") . | indent 4 }}
  signer-config.json: |
{{ tpl (.Files.Get "files/signer-config.json") . | indent 4 }}