{{- if (and (not .Values.storage.remote.enabled) (not (eq .Values.storage.flavor "memory"))) }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: notary
    app.kubernetes.io/component: notary-db
  name: notary-db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notary
        app.kubernetes.io/component: notary-db
    spec:
      initContainers:
      - command:
        - /gomplate
        - --left-delim
        - '%%'
        - --right-delim
        - '%%'
        - --input-dir
        - /sql-init-templates
        - --output-dir
        - /docker-entrypoint-initdb.d
        image: hairyhenderson/gomplate:v3
        name: gomplate
        env:
        - name: SERVERPASSWORD
          {{- if .Values.server.storageCredentials.password }}
          valueFrom:
            secretKeyRef:
              name: server-password
              key: password
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.server.storageCredentials.passwordSecretName }}
              key: {{ .Values.server.storageCredentials.passwordSecretKey }}
          {{- end }}
        - name: SIGNERPASSWORD
          {{- if .Values.signer.storageCredentials.password }}
          valueFrom:
            secretKeyRef:
              name: signer-password
              key: password
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.signer.storageCredentials.passwordSecretName }}
              key: {{ .Values.signer.storageCredentials.passwordSecretKey }}
          {{- end }}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: sql-init
        - mountPath: /sql-init-templates
          name: notarysql
      containers:
      {{- if eq .Values.storage.flavor "mysql" }}
      - args:
        - mysqld
        - --innodb_file_per_table
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: {{ .Values.storage.kubernetes.image }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: notary-data
      {{- else if eq .Values.storage.flavor "postgres" }}
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        image: {{ .Values.storage.kubernetes.image }}
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: notary-data
      {{- end }}
        - mountPath: /docker-entrypoint-initdb.d
          name: sql-init
        - mountPath: /sql-init-templates
          name: notarysql
      volumes:
      - name: notary-data
        persistentVolumeClaim:
          claimName: notary-data
      - name: notarysql
        configMap:
          name: notarysql
      - name: sql-init
        emptyDir: {}

---

{{- end }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: notary
    app.kubernetes.io/component: notaryserver
  name: notaryserver
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notary
        app.kubernetes.io/component: notaryserver
    spec:
      initContainers:
      - command:
        - /gomplate
        - --left-delim
        - '%%'
        - --right-delim
        - '%%'
        - --input-dir
        - /config-template
        - --output-dir
        - /config
        image: hairyhenderson/gomplate:v3
        name: gomplate
        env:
        - name: PASSWORD
          {{- if .Values.server.storageCredentials.password }}
          valueFrom:
            secretKeyRef:
              name: server-password
              key: password
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.server.storageCredentials.passwordSecretName }}
              key: {{ .Values.server.storageCredentials.passwordSecretKey }}
          {{- end }}
        volumeMounts:
        - mountPath: /config
          name: config-rendered
        - mountPath: /config-template
          name: config-template
      containers:
      - command:
        - notary-server
        - -config=/config/server-config.json
        image: notary:{{ .Values.server.version }}
        name: server
        ports:
        - containerPort: {{ .Values.server.port }}
          name: https
        volumeMounts:
        - mountPath: /config
          name: config-rendered
        - mountPath: /tls
          name: tls
      volumes:
      - configMap:
          name: notary-config
        name: config-template
      - secret:
          secretName: notary-tls
        name: tls
      - emptyDir: {}
        name: config-rendered

{{- if eq .Values.server.trust.type "remote" }}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: notary
    app.kubernetes.io/component: notarysigner
  name: notarysigner
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notary
        app.kubernetes.io/component: notarysigner
    spec:
      initContainers:
      - command:
        - /gomplate
        - --left-delim
        - '%%'
        - --right-delim
        - '%%'
        - --input-dir
        - /config-template
        - --output-dir
        - /config
        image: hairyhenderson/gomplate:v3
        name: gomplate
        env:
        - name: PASSWORD
          {{- if .Values.signer.storageCredentials.password }}
          valueFrom:
            secretKeyRef:
              name: signer-password
              key: password
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.signer.storageCredentials.passwordSecretName }}
              key: {{ .Values.signer.storageCredentials.passwordSecretKey }}
          {{- end }}
        volumeMounts:
        - mountPath: /config
          name: config-rendered
        - mountPath: /config-template
          name: config-template
      containers:
      - command:
        - notary-signer
        - -config=/config/signer-config.json
        image: notary:{{ .Values.signer.version }}
        name: signer
        env:
        - name: NOTARY_SIGNER_{{ .Values.signer.alias.defaultAlias | upper }}
          {{- if .Values.signer.alias.aliasPassphrase }}
          valueFrom:
            secretKeyRef:
              name: signer-alias
              key: alias-secret
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.signer.alias.aliasSecretName }}
              key: {{ .Values.signer.alias.aliasSecretKey }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.signer.port }}
          name: https
        volumeMounts:
        - mountPath: /config
          name: config-rendered
        - mountPath: /tls
          name: tls
      volumes:
      - configMap:
          name: notary-config
        name: config-template
      - secret:
          secretName: notary-tls
        name: tls
      - emptyDir: {}
        name: config-rendered

{{- end }}