{{- if eq .Values.server.trust.type "remote" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "notary.fullname" . }}-notarysigner
spec:
  ports:
  - name: https
    port: {{ .Values.signer.port }}
    targetPort: {{ .Values.signer.port }}
  selector:
    service: {{ template "notary.fullname" . }}-signer

---

{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "notary.fullname" . }}-server
spec:
  ports:
  - name: https
    port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}
  selector:
    service: {{ template "notary.fullname" . }}-server

---

{{- if not (eq .Values.storage.type "memory") }}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "notary.fullname" . }}-db
spec:
  ports:
  {{- if eq .Values.storage.type "mysql" }}
  - name: mysql
    port: 3306
    targetPort: 3306
  {{- else if eq .Values.storage.type "postgres" }}
  - name: postgres
    port: 5432
    targetPort: 5432
  {{- end }}
  selector:
    service: {{ template "notary.fullname" . }}-db

{{- end }}